//! PHP-FPM supervision. Every site gets its own FPM master (one pool),
//! started through an optional launcher: a uid/gid switch and a sandbox
//! wrapper (`nova sandbox ... --`) that applies Landlock before exec. NOVA
//! waits until the pool answers a FastCGI ping, restarts the master with
//! backoff if it dies, and stops it gracefully.
//!
//! Secrets and environment values never appear in the generated files: each
//! value is placed in the FPM master's environment under a generated name and
//! the pool references it with `env[NAME] = $GENERATED`. With `clear_env = yes`
//! workers only see their own variables.

use crate::client::{self, PhpRequest};
use std::collections::BTreeMap;
use std::ffi::OsString;
use std::fmt::Write as _;
use std::io;
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::{Duration, Instant};
use tokio::io::{AsyncBufReadExt, AsyncReadExt, BufReader};
use tokio::net::unix::pipe;
use tokio::process::{Child, Command};
use tokio::sync::watch;

pub const PING_PATH: &str = "/__nova_fpm_ping";

#[derive(Debug, Clone)]
pub struct PoolSpec {
    pub site: String,
    pub socket: PathBuf,
    /// Project directory; the only tree (besides `state_dir`) PHP may open.
    pub project_dir: PathBuf,
    /// Per-site writable directory for tmp files, uploads and sessions.
    pub state_dir: PathBuf,
    pub env: BTreeMap<String, String>,
    pub max_children: u32,
    pub max_requests: u32,
    pub memory_limit: String,
    pub timeout_secs: u64,
    pub upload_max: String,
    pub disable_functions: Vec<String>,
    pub ini: BTreeMap<String, String>,
    /// Startup-only settings (OPcache, JIT, realpath cache) passed to the
    /// master as `-d key=value`; pools cannot change them per request.
    pub master_ini: BTreeMap<String, String>,
    pub display_errors: bool,
    /// Also set PHP's `open_basedir`. Only needed when the kernel sandbox is
    /// not guaranteed: open_basedir disables PHP's realpath cache, which
    /// makes framework-heavy apps several times slower under load.
    pub open_basedir: bool,
}

impl PoolSpec {
    fn env_var_name(&self, key: &str) -> String {
        format!(
            "NOVA_POOL_{}_{}",
            self.site.to_ascii_uppercase().replace('-', "_"),
            key
        )
    }
}

/// How the FPM master is started.
#[derive(Debug, Clone, Default)]
pub struct Launch {
    /// Switch to this uid/gid (requires a privileged parent). Supplementary
    /// groups are cleared.
    pub user: Option<(u32, u32)>,
    /// Command prefix, e.g. `["/usr/local/bin/nova", "sandbox", ..., "--"]`.
    pub wrapper: Vec<OsString>,
}

pub struct FpmConfig {
    pub binary: PathBuf,
    /// Generated configuration file (readable by the FPM user).
    pub conf_path: PathBuf,
    /// Directory for the pid file; the socket lives in `pool.socket`.
    pub run_dir: PathBuf,
    pub pool: PoolSpec,
    pub shutdown_grace: Duration,
    pub launch: Launch,
}

impl FpmConfig {
    pub fn render(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(
            s,
            "; Generated by NOVA. Do not edit; changes are overwritten on start."
        );
        let _ = writeln!(s, "[global]");
        let _ = writeln!(s, "pid = {}", self.run_dir.join("php-fpm.pid").display());
        let _ = writeln!(s, "error_log = /proc/self/fd/2");
        let _ = writeln!(s, "log_level = notice");
        let _ = writeln!(s, "log_limit = 8192");
        let _ = writeln!(s, "daemonize = no");
        let _ = writeln!(s, "emergency_restart_threshold = 10");
        let _ = writeln!(s, "emergency_restart_interval = 1m");
        let _ = writeln!(
            s,
            "process_control_timeout = {}s",
            self.shutdown_grace.as_secs().max(1)
        );
        s.push('\n');
        s.push_str(&render_pool(&self.pool));
        s
    }

    /// Environment for the FPM master: a minimal base plus the pool's values.
    pub fn master_env(&self) -> Vec<(String, String)> {
        let mut env = vec![(
            "PATH".to_string(),
            "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".to_string(),
        )];
        for (k, v) in &self.pool.env {
            env.push((self.pool.env_var_name(k), v.clone()));
        }
        env
    }

    fn command(&self) -> Command {
        let mut cmd = match self.launch.wrapper.split_first() {
            Some((program, args)) => {
                let mut c = Command::new(program);
                c.args(args).arg(&self.binary);
                c
            }
            None => Command::new(&self.binary),
        };
        for (k, v) in &self.pool.master_ini {
            cmd.arg("-d").arg(format!("{k}={v}"));
        }
        if let Some((uid, gid)) = self.launch.user {
            cmd.uid(uid).gid(gid);
        }
        cmd.env_clear().envs(self.master_env()).stdin(Stdio::null());
        cmd
    }
}

pub fn render_pool(p: &PoolSpec) -> String {
    let mut s = String::new();
    let tmp = p.state_dir.join("tmp");
    let sessions = p.state_dir.join("sessions");
    let _ = writeln!(s, "[{}]", p.site);
    let _ = writeln!(s, "listen = {}", p.socket.display());
    // The socket's directory (owner: site, group: worker, mode 0710) is the
    // access control; Landlock additionally hides it from other sites.
    let _ = writeln!(s, "listen.mode = 0666");
    // ondemand: no idle workers for quiet sites; each request runs in a
    // classic, isolated PHP request lifecycle.
    let _ = writeln!(s, "pm = ondemand");
    let _ = writeln!(s, "pm.max_children = {}", p.max_children);
    let _ = writeln!(s, "pm.process_idle_timeout = 30s");
    let _ = writeln!(s, "pm.max_requests = {}", p.max_requests);
    let _ = writeln!(s, "ping.path = {PING_PATH}");
    let _ = writeln!(s, "ping.response = pong");
    let _ = writeln!(s, "request_terminate_timeout = {}s", p.timeout_secs + 5);
    let _ = writeln!(s, "catch_workers_output = yes");
    let _ = writeln!(s, "decorate_workers_output = no");
    let _ = writeln!(s, "clear_env = yes");
    let _ = writeln!(s, "security.limit_extensions = .php");
    let _ = writeln!(s, "chdir = {}", p.project_dir.display());
    for k in p.env.keys() {
        let _ = writeln!(s, "env[{k}] = ${}", p.env_var_name(k));
    }
    let basedir = format!("{}:{}", p.project_dir.display(), p.state_dir.display());
    let mut admin: BTreeMap<&str, String> = BTreeMap::new();
    if p.open_basedir {
        admin.insert("open_basedir", basedir);
    }
    admin.insert("sys_temp_dir", tmp.display().to_string());
    admin.insert("upload_tmp_dir", tmp.display().to_string());
    admin.insert("session.save_path", sessions.display().to_string());
    admin.insert("memory_limit", p.memory_limit.clone());
    admin.insert("max_execution_time", p.timeout_secs.to_string());
    admin.insert("upload_max_filesize", p.upload_max.clone());
    admin.insert("post_max_size", p.upload_max.clone());
    admin.insert("disable_functions", p.disable_functions.join(","));
    for (k, v) in &p.ini {
        admin.insert(k, v.clone());
    }
    for (k, v) in admin {
        let _ = writeln!(s, "php_admin_value[{k}] = {v}");
    }
    let _ = writeln!(s, "php_admin_flag[expose_php] = off");
    let _ = writeln!(s, "php_admin_flag[log_errors] = on");
    let _ = writeln!(
        s,
        "php_flag[display_errors] = {}",
        if p.display_errors { "on" } else { "off" }
    );
    s
}

/// Handle to the supervised FPM process.
pub struct Fpm {
    ready: watch::Receiver<bool>,
    stop: watch::Sender<bool>,
    task: tokio::task::JoinHandle<()>,
}

impl Fpm {
    /// Write configuration, verify it with `php-fpm -t`, and start supervising.
    pub async fn start(cfg: FpmConfig) -> io::Result<Self> {
        prepare(&cfg).await?;
        let (ready_tx, ready) = watch::channel(false);
        let (stop, stop_rx) = watch::channel(false);
        let task = tokio::spawn(supervise(cfg, ready_tx, stop_rx));
        Ok(Self { ready, stop, task })
    }

    pub fn ready(&self) -> watch::Receiver<bool> {
        self.ready.clone()
    }

    /// Wait until the pool responds, or fail after `timeout`.
    pub async fn wait_ready(&self, timeout: Duration) -> bool {
        let mut rx = self.ready.clone();
        tokio::time::timeout(timeout, rx.wait_for(|r| *r))
            .await
            .is_ok_and(|r| r.is_ok())
    }

    /// Graceful stop: SIGQUIT lets workers finish, SIGKILL after the grace period.
    pub async fn shutdown(self) {
        let _ = self.stop.send(true);
        let _ = self.task.await;
    }
}

async fn prepare(cfg: &FpmConfig) -> io::Result<()> {
    tokio::fs::write(&cfg.conf_path, cfg.render()).await?;
    let (mut rx, w) = log_pipe(cfg.launch.user)?;
    let mut child = cfg
        .command()
        .arg("-t")
        .arg("-y")
        .arg(&cfg.conf_path)
        .stdout(Stdio::from(w.try_clone()?))
        .stderr(Stdio::from(w))
        .spawn()
        .map_err(|e| {
            io::Error::new(
                e.kind(),
                format!("cannot run {}: {e}", cfg.binary.display()),
            )
        })?;
    let mut output = Vec::new();
    let (status, _) = tokio::join!(child.wait(), rx.read_to_end(&mut output));
    if !status?.success() {
        return Err(io::Error::other(format!(
            "php-fpm rejected the configuration for site {}:\n{}",
            cfg.pool.site,
            String::from_utf8_lossy(&output)
        )));
    }
    Ok(())
}

/// A pipe for FPM's stdout/stderr whose write end belongs to the FPM user.
/// FPM reopens its log via `/proc/self/fd/2`, which the kernel only permits
/// for the inode's owner; a pipe created by a root parent would be refused.
fn log_pipe(user: Option<(u32, u32)>) -> io::Result<(pipe::Receiver, OwnedFd)> {
    let mut fds = [0; 2];
    // SAFETY: pipe2 fills two valid descriptors on success; we take ownership immediately.
    if unsafe { libc::pipe2(fds.as_mut_ptr(), libc::O_CLOEXEC) } != 0 {
        return Err(io::Error::last_os_error());
    }
    let (r, w) = unsafe { (OwnedFd::from_raw_fd(fds[0]), OwnedFd::from_raw_fd(fds[1])) };
    if let Some((uid, gid)) = user {
        // SAFETY: fchown on a descriptor we own.
        if unsafe { libc::fchown(w.as_raw_fd(), uid, gid) } != 0 {
            return Err(io::Error::last_os_error());
        }
    }
    // SAFETY: fcntl on a descriptor we own.
    unsafe {
        let flags = libc::fcntl(r.as_raw_fd(), libc::F_GETFL);
        libc::fcntl(r.as_raw_fd(), libc::F_SETFL, flags | libc::O_NONBLOCK);
    }
    Ok((pipe::Receiver::from_owned_fd(r)?, w))
}

fn spawn_child(cfg: &FpmConfig) -> io::Result<Child> {
    let _ = std::fs::remove_file(&cfg.pool.socket);
    let (rx, w) = log_pipe(cfg.launch.user)?;
    let child = cfg
        .command()
        .arg("--nodaemonize")
        .arg("--force-stderr")
        .arg("-y")
        .arg(&cfg.conf_path)
        .stdout(Stdio::from(w.try_clone()?))
        .stderr(Stdio::from(w))
        .kill_on_drop(true)
        .spawn()?;
    // Forward FPM and worker output into NOVA's structured log.
    tokio::spawn(forward_lines(rx, cfg.pool.site.clone()));
    Ok(child)
}

async fn forward_lines(r: impl tokio::io::AsyncRead + Unpin, site: String) {
    let mut lines = BufReader::new(r).lines();
    while let Ok(Some(line)) = lines.next_line().await {
        if !line.trim().is_empty() {
            tracing::info!(target: "nova::php_fpm", site, "{line}");
        }
    }
}

/// FastCGI ping through the real request path.
pub async fn ping(socket: &Path) -> bool {
    let params = vec![
        (b"REQUEST_METHOD".to_vec(), b"GET".to_vec()),
        (b"SCRIPT_NAME".to_vec(), PING_PATH.as_bytes().to_vec()),
        (b"SCRIPT_FILENAME".to_vec(), PING_PATH.as_bytes().to_vec()),
    ];
    let req = PhpRequest {
        socket: socket.to_owned(),
        params,
        body: futures_util::stream::empty(),
        header_timeout: Duration::from_secs(2),
        site: String::new(),
    };
    matches!(client::execute(req).await, Ok(r) if r.status.is_success())
}

async fn supervise(cfg: FpmConfig, ready: watch::Sender<bool>, mut stop: watch::Receiver<bool>) {
    let mut backoff = Duration::from_millis(500);
    loop {
        let mut child = match spawn_child(&cfg) {
            Ok(c) => c,
            Err(e) => {
                tracing::error!(site = cfg.pool.site, error = %e, "failed to start php-fpm");
                if wait_or_stop(&mut stop, backoff).await {
                    return;
                }
                backoff = (backoff * 2).min(Duration::from_secs(30));
                continue;
            }
        };
        let started = Instant::now();
        tracing::info!(
            site = cfg.pool.site,
            pid = child.id(),
            uid = cfg.launch.user.map(|u| u.0),
            "php-fpm started"
        );

        // Readiness: poll until every pool answers, while watching for exit/stop.
        let mut probe = tokio::time::interval(Duration::from_millis(100));
        let exit = loop {
            tokio::select! {
                status = child.wait() => break Some(status),
                _ = stop.changed() => break None,
                _ = probe.tick(), if !*ready.borrow() => {
                    if ping(&cfg.pool.socket).await {
                        tracing::info!(site = cfg.pool.site, elapsed_ms = started.elapsed().as_millis() as u64, "php-fpm ready");
                        let _ = ready.send(true);
                    }
                }
            }
        };
        let _ = ready.send(false);

        match exit {
            None => {
                stop_child(&mut child, cfg.shutdown_grace).await;
                return;
            }
            Some(status) => {
                tracing::error!(
                    site = cfg.pool.site,
                    ?status,
                    "php-fpm exited unexpectedly; restarting"
                );
                if started.elapsed() > Duration::from_secs(30) {
                    backoff = Duration::from_millis(500);
                }
                if wait_or_stop(&mut stop, backoff).await {
                    return;
                }
                backoff = (backoff * 2).min(Duration::from_secs(30));
            }
        }
    }
}

/// Sleep for `d`; returns true if a stop was requested meanwhile.
async fn wait_or_stop(stop: &mut watch::Receiver<bool>, d: Duration) -> bool {
    tokio::select! {
        _ = tokio::time::sleep(d) => *stop.borrow(),
        _ = stop.changed() => true,
    }
}

async fn stop_child(child: &mut Child, grace: Duration) {
    if let Some(pid) = child.id() {
        // SIGQUIT = graceful shutdown for php-fpm (workers finish current requests).
        // SAFETY: plain kill(2) on our own child's pid.
        unsafe {
            libc::kill(pid as libc::pid_t, libc::SIGQUIT);
        }
    }
    match tokio::time::timeout(grace, child.wait()).await {
        Ok(status) => tracing::info!(?status, "php-fpm stopped"),
        Err(_) => {
            tracing::warn!("php-fpm did not stop within {grace:?}; killing");
            let _ = child.kill().await;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> PoolSpec {
        PoolSpec {
            site: "my-site".into(),
            socket: "/run/nova/php/my-site/fpm.sock".into(),
            project_dir: "/srv/sites/my-site".into(),
            state_dir: "/var/lib/nova/sites/my-site".into(),
            env: BTreeMap::from([("DB_PASSWORD".into(), "s3cr\"et$x\n".into())]),
            max_children: 4,
            max_requests: 100,
            memory_limit: "128M".into(),
            timeout_secs: 30,
            upload_max: "64M".into(),
            disable_functions: vec!["exec".into(), "system".into()],
            ini: BTreeMap::from([("memory_limit".into(), "512M".into())]),
            master_ini: BTreeMap::new(),
            display_errors: false,
            open_basedir: true,
        }
    }

    #[test]
    fn pool_isolates_filesystem_and_env() {
        let conf = render_pool(&spec());
        assert!(conf.contains(
            "php_admin_value[open_basedir] = /srv/sites/my-site:/var/lib/nova/sites/my-site\n"
        ));
        assert!(conf.contains("clear_env = yes"));
        assert!(conf.contains("env[DB_PASSWORD] = $NOVA_POOL_MY_SITE_DB_PASSWORD\n"));
        assert!(conf.contains("php_admin_value[disable_functions] = exec,system\n"));
        // Site ini overrides defaults instead of duplicating them.
        assert!(conf.contains("php_admin_value[memory_limit] = 512M\n"));
        assert_eq!(conf.matches("memory_limit").count(), 1);
        // The secret value itself never reaches the config file.
        assert!(!conf.contains("s3cr"));
    }

    #[test]
    fn open_basedir_only_when_requested() {
        let conf = render_pool(&PoolSpec {
            open_basedir: false,
            ..spec()
        });
        assert!(!conf.contains("open_basedir"));
    }

    #[test]
    fn secrets_travel_through_master_env() {
        let cfg = FpmConfig {
            binary: "php-fpm".into(),
            conf_path: "/run/nova/conf/my-site.conf".into(),
            run_dir: "/run/nova/php/my-site".into(),
            pool: spec(),
            shutdown_grace: Duration::from_secs(10),
            launch: Launch::default(),
        };
        let env = cfg.master_env();
        assert!(
            env.iter()
                .any(|(k, v)| k == "NOVA_POOL_MY_SITE_DB_PASSWORD" && v == "s3cr\"et$x\n")
        );
        let conf = cfg.render();
        assert!(conf.contains("[my-site]"));
        assert!(conf.contains("pid = /run/nova/php/my-site/php-fpm.pid"));
    }
}
