[package]
name = "nova-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.104"
bcrypt = "0.19.3"
bytes = "1.12.1"
futures-util = "0.3.34"
http = "1.5.0"
http-body-util = "0.1.5"
hyper = { version = "1.12.0", features = ["client", "http1"] }
lol_html = "2"
mysql_async = { version = "0.37.1", default-features = false, features = ["binlog", "minimal-rust"] }
hyper-util = { version = "0.1.21", features = ["client-legacy", "http1", "tokio"] }
libc = "0.2.190"
nova-config = { version = "0.1.0", path = "../nova-config" }
nova-http = { version = "0.1.0", path = "../nova-http" }
nova-optimize = { version = "0.1.0", path = "../nova-optimize" }
nova-runtime-php = { version = "0.1.0", path = "../nova-runtime-php" }
nova-security = { version = "0.1.0", path = "../nova-security" }
percent-encoding = "2.3.2"
rcgen = { version = "0.14.10", default-features = false, features = ["aws_lc_rs", "pem"] }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs", "prefer-post-quantum", "std", "tls12", "logging"] }
rustls-acme = { version = "0.15.4", default-features = false, features = ["aws-lc-rs", "tokio", "webpki-roots", "tls12"] }
serde_json = "1.0.151"
socket2 = { version = "0.6", features = ["all"] }
tokio = { version = "1.53.2", features = ["full"] }
tracing = "0.1.44"

[dev-dependencies]
hyper = { version = "1.12.0", features = ["server", "http1"] }
